@startuml

object Cliente
object Frontend
object ResgateController
object ResgateService
object CustomerRepository
object ResgateRepository
object BancoDeDados

Cliente --> Frontend : 1: solicitarResgate()

Frontend --> ResgateController : 2: criarSolicitacao()

ResgateController --> ResgateService : 3: solicitarResgate()

ResgateService --> CustomerRepository : 4: buscarCliente()

CustomerRepository --> BancoDeDados : 5: SELECT

BancoDeDados --> CustomerRepository : 6: cliente

CustomerRepository --> ResgateService : 7: cliente

ResgateService --> ResgateService : 8: validarPontos()

ResgateService --> ResgateRepository : 9: salvar()

ResgateRepository --> BancoDeDados : 10: INSERT

BancoDeDados --> ResgateRepository : 11: solicitação

ResgateRepository --> ResgateService : 12: solicitação

ResgateService --> ResgateController : 13: sucesso

ResgateController --> Frontend : 14: resposta

Frontend --> Cliente : 15: solicitação registrada

@enduml