@startuml

[*] --> Criado

Criado --> Processando : pagamento confirmado

Processando --> Confirmado : pedido validado

Confirmado --> Entregue : entrega realizada

Entregue --> Finalizado : pedido encerrado

Criado --> Cancelado : cancelamento

Processando --> Cancelado : cancelamento

Confirmado --> Cancelado : cancelamento

Cancelado --> [*]

Finalizado --> [*]

@enduml